### ISSUE TITLE
Redirection non souhaitée lorsque le tag "filter" est utilisé par un snippet

### ISSUE THREAD

**Issue by zertrin** [broncowdd/SnippetVamp#54]
Le bug est plus général que ca, mais je suis tombé dessus dans le cas du tag `filter`.

Lorsque le tag `filter` est utilisé pour tagguer un snippet, le fait de cliquer sur le titre du snippet redirige immédiatement sur la page `http(s)://snippetvamp.example.org/?tag`. En outre d'empêcher l'affichage du snippet souhaité, la page `?tag` ne montre qu'un sous-ensemble des snippets peu utile.

Après des mois à ne pas trop comprendre pourquoi je n'avais qu'un snippet de concerné, je suis tombé sur ce petit morceau de JS qui a fait déclic:

```
        $(".filter").click(function(){
            tags='https://snippet.example.org/?tag=';
            $(".tag_cloud a .tagcheck").each(function(){
                if ($(this).attr('checked')==true){tags=tags+$(this).attr('name')+'+';}
            });
            tags=tags.substring(0,tags.length-1);
            document.location.href=tags;
            return false;
        });
```

et comme les tags sont utilisés en tant que classe dans le titre des snippets : 

```
<h1 class="snippet_title toggle_next mail sieve filter prive " title="mail sieve"> Sieve Refilter INBOX </h1>
```

Badaboom, le tag que j'avais choisi en tant qu'utilisateur (`filter`) est en conflit avec `$(".filter").click()`.

De manière générale je m'interroge sur la pertinence d'utiliser les tags provenant des utilisateurs dans les classes des titres... Un autre Tag qui pourrait entrer en conflit par exemple : `multiselect`

**Comment by broncowdd** [comment]
Oui, c'est vrai qu'il faut que je change ça, ne serait-ce qu'avec une classe spécifique, genre class="snippetVamp_[tag]" qui provoquerait moins de conflits... Je corrige asap: merci beaucoup ;-)

**Comment by zertrin** [comment]
euh le commit 061e8b3 me semble louche, il revert snippetvamp à la version 1.83 et défait bcp de choses.

Il semblerait que tu ne sois pas parti de la dernière version pour faire ce commit.

**Comment by broncowdd** [comment]
oops, zut flute et cacaboudin: c'est ça de faire des corrections sur mon portable depuis le boulot ^^ je corrige asap ;-)

**Comment by broncowdd** [comment]
J'ai corrigé, ça devrait le faire.
